name: the_cutting_machinery
description: A meditation app for the heavy cutting of enlightenment meditation practice
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1
  provider: ^6.0.1
  flutter_svg: ^0.23.0
  just_audio: ^0.9.17
  audio_service: ^0.18.3
  rxdart: ^0.27.2
  intl: ^0.18.1
  shared_preferences: ^2.1.0
  firebase_core: ^2.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true
  web: true
