/* IGNORING FOR LOCAL WORK

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvUech_gIfgGIkIXBLAZK1uApqaCgpS9M',
    appId: '1:277214271986:web:c505a5e29752f8ce80f36b',
    messagingSenderId: '277214271986',
    projectId: 'the-cutting-machinery',
    authDomain: 'the-cutting-machinery.firebaseapp.com',
    storageBucket: 'the-cutting-machinery.appspot.com',
    measurementId: 'G-1SHC6T1T6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIREVjudqvhstyWCD86HVo3fzIOhyXIuo',
    appId: '1:277214271986:android:4a71f532932f01a780f36b',
    messagingSenderId: '277214271986',
    projectId: 'the-cutting-machinery',
    storageBucket: 'the-cutting-machinery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ezaHEmeYkniuuESN6rXfsBm7jrJjLDY',
    appId: '1:277214271986:ios:3a2b131cf303e0ea80f36b',
    messagingSenderId: '277214271986',
    projectId: 'the-cutting-machinery',
    storageBucket: 'the-cutting-machinery.appspot.com',
    iosClientId: '277214271986-qs739mofebnadl23liihu2lf1jkp2dtc.apps.googleusercontent.com',
    iosBundleId: 'com.example.theCuttingMachinery',
  );
}

*/